services:
  mongodb1:
    image: mongo:latest
    container_name: mongodb1
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dwi
      MONGO_INITDB_ROOT_PASSWORD: dwi
      MONGO_INITDB_DATABASE: admin
    volumes:
      - "mongo-data1:/data/db"
  mongodb2:
    image: mongo:latest
    container_name: mongodb2
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dwi
      MONGO_INITDB_ROOT_PASSWORD: dwi
      MONGO_INITDB_DATABASE: admin
    volumes:
      - type: volume
        source: mongo-data2
        target: "/data/db"
        read_only: false

volumes:
  mongo-data1:
    name: mongo-data1
  mongo-data2:
    name: mongo-data2
# backup volume
# docker container run --rm --name ubuntubackup --mount "type=bind,source=${PWD}/backup,destination=/backup" --mount "type=volume,source=mongo-data1,destination=/data" ubuntu:latest tar cvf /backup/backup.tar.gz /data
