services:
  app:
    container_name: app
    build:
      context: "./app"
      dockerfile: Dockerfile
    image: "app-golang:1.0.0"
    environment:
      - "APP_PORT=8080"
      - "MODE=local"
    ports:
      - "8080:8080"

# script
# docker compose -f docker-compose.yaml -f dev.yaml create
# docker compose up --build -f docker-compose.yaml -f prod.yaml