services:
  # This is example nginx
  nginx-example:
    image: nginx:latest
    container_name: nginx-example
  # This is example mongodb
  mongo-example:
    image: mongo:latest
    container_name: mongo-example
